### ISSUE TITLE
Import Static Props

### ISSUE THREAD

**Issue by snake-biscuits** [snake-biscuits/io_import_rbsp#7]
Should collab w/ other addons like [Perimeter](https://github.com/EM4Volts/Perimeter)
`.rpak` tools will be a must

## Formats
 - [ ] **Titanfall**: Source Engine `.mdl` v46
 - [ ] **Titanfall | 2**: Titanfall Engine `.mdl`
 - [ ] **Apex Legends**: Titanfall Engine `.rmdl`

## Settings
 * Physics Model Only
 * Maximum LoD level
 * Can we do multiple *LoD* per-instance?
   - Simulate LoD switching?

### Prerequisites
 - [ ] #2

**Comment by snake-biscuits** [comment]
It's possible to import [SourceIO](https://github.com/REDxEYE/SourceIO) in Blender Python, provided it's installed & available
We could probably rig up a bulk asset importer for Titanfall that hooks that

```python
try:
    import SourceIO
except ImportError:
    pass  # switch to our own implementation / disable feature

# OR

import importlib
if importlib.util.find_spec("SourceIO") is None:
    ...  # disable prop loading feature
```

> imo option 2 is better, as we can use a `is_SourceIO_available` global

Titanfall 2 `.mdl` / Apex `.rmdl` support might require collabing w/ SourceIO devs
A fork or PR of SourceIO is an idea, but I'd want to check w/ the devs first to make sure they'd be OK with that

Otherwise we just build our own importer

> availability could get wierd depending on the order addons are initialised & cached in
> I haven't encountered inter-addon dependencies before so idk

**Comment by snake-biscuits** [comment]
To figure out what parts of SourceIO to use, I'd trace backwards from operators
e.g. [SOURCEIO_OT_BSPImport](https://github.com/REDxEYE/SourceIO/blob/master/blender_bindings/operators/source1_operators.py#L111)
We'd have to implement our own content manager for Titanfall Engine assets
I still think hooking the `.mdl` importer would be less work than building our own

**Comment by snake-biscuits** [comment]
nvm, SourceIO doesn't bulk load static props like I thought it did
we'd be better off w/ our own importer:
 * Instanced props
 * Blender Asset System
 * Less debugging nightmares

**Comment by snake-biscuits** [comment]
Built a decent `.mdl` importer for `ass` this week
Going to need to make some fairly major refactors to work it in tho:

## TODOs

 * split case-insensitve asset search into it's own utility function
   will be used for: `.mdl` models, materials & textures

### `load.geometry`
 * refactor `all_models`
   - `model_to_blender`
     ass.Model -> Blender data
     placeholder materials


### `load.materials`
 * refactor `NodeMaker.material_from_name`
   - `make_placeholder(material.name)`
     use custom data
   - `update_from_rsx(material)`
   - `WLD_MATL.from_name`
   - `FIX_MATL.from_name`
 * eliminate duplicate texture loads
   - need a better check than `filename in bpy.data.images`
 * expose material loading to UI for testing
   - `WLD_MATL.from_name`
   - `FIX_MATL.from_name`
   - `VMT.from_name`


### `load.props`
 * refactor `static_prop`
   - `ass.scene.valve.Mdl` -> `ass.Model` -> Blender data
     reuse `load.geometry.as_blender_model`
 * expose prop loading to UI for testing
   - `import Titanfall 2 v53 MDL (*.mdl)`
